kill(all)$
/* This requires the Clifford algebra package in your Maxima load path */
/* GitHUb: https://github.com/dprodanov/clifford */
load("clifford")$
load("cliffordan")$

clifford(ee,3)$
declare([x, y, z], scalar)$
ct_coords : [x, y, z]$
xpos : x*ee[1] + y*ee[2] + z*ee[3]$

curl(A) := -grpart( mvectdiff(A,xpos), 2 ) | %iv$
div(A) := grpart( mvectdiff(A,xpos), 0 )$
cross(A,B) := -(A & B) | %iv$

zbl : [BB[1]=0, BB[2]=0, BB[3]=0];

depends([BB, uu], [x,y,z])$
depends([p, rho], [x,y,z])$
declare([mu_0, p, rho], scalar)$
assume(p>0)$
assume(rho>0)$
assume(mu_0>0)$
assume(gamma>0)$

B : cvect(BB)$
u : cvect(uu)$

J : curl(B)/mu_0$
E : -cross(u, B)$

/* Construct the ideal MHD equations in quasilinear form */
dt_rho : grpart(mvectdiff(rho*u, xpos), 0)$
dt_u : cdirdiff(u, u, xpos) + 1/rho*mvectdiff(p,xpos) - cross(J,B)/rho$
dt_B : curl(E)$
dt_p : cdirdiff(p, u, xpos) + gamma*p*div(u)$

/* Split into components and put into a list */
dt_All : [dt_rho, dt_u | ee[1], dt_u | ee[2], dt_u | ee[3], dt_B | ee[1], dt_B | ee[2], dt_B | ee[3], dt_p ]$

meqn : length(dt_All)$

/* Transform from primitive to conserved variables */
phi_v : [rho, rho*(u|ee[1]), rho*(u|ee[2]), rho*(u|ee[3]), B|ee[1], B|ee[2], B|ee[3], 1/2*rho*(u | u) + p/(gamma-1) + (B|B)/(2*mu_0)]$
primvec : [rho, u|ee[1], u|ee[2], u|ee[3], B|ee[1], B|ee[2], B|ee[3], p ]$
phi_prime_ij [i,j] := diff(phi_v[i], primvec[j])$
phi_prime : genmatrix(phi_prime_ij, meqn, meqn)$

/** Compute inverse transform */
phi_prime_inv : fullratsimp(invert(phi_prime))$

calcev(dir) := block([diff_list,v:ct_coords[dir], Atm, vals, vects, Evs, Rev, Rev_fj, Lev_fj],

  diff_list : [diff(rho,v), diff(uu[1],v), diff(uu[2],v), diff(uu[3],v), diff(BB[1],v), diff(BB[2],v), diff(BB[3],v),  diff(p,v) ],

  Atm : coefmatrix(dt_All, diff_list),
  [vals, vects] : eigenvectors(Atm),
  
  Evs : (Evs : [], for i from 1 thru length(vals[1])
        do (for j from 1 thru vals[2][i]
	  do (Evs : append(Evs, [vals[1][i]]))), Evs),

  Rev : (Rev : matrix([]), for i from 1 thru length (vals[1]) 
        do (for j from 1 thru vals[2][i] 
          do ( (Rev : addcol(Rev, transpose(matrix(vects[i][j])))))), Rev),

  Evs : letsimp( expand(Evs) ),
  Rev : letsimp( Rev ),
  Lev : invert(Rev),

  return ([Evs, Rev, Lev])
  )$

res : calcev(1)$
