#! /usr/bin/env python


top = '.'

from waflib import Configure, Logs, Utils

def options(opt):
        opt.load('compiler_cxx')
        
def configure(conf):
	conf.load('compiler_cxx')
	conf.env.append_value('CXXFLAGS', '-O3')

def build(bld):
        bld.shlib(
	        source = 'fpo-kernels.cpp',
	        target = 'fpo-kernels')
