kill(all)$
/* This requires the Clifford algebra package in your Maxima load path */
/* GitHUb: https://github.com/dprodanov/clifford */
load("clifford")$
load("cliffordan")$

clifford(ee,3)$
declare([x, y, z], scalar)$
ct_coords : [x, y, z]$
xpos : x*ee[1] + y*ee[2] + z*ee[3]$

curl(A) := -grpart( mvectdiff(A,xpos), 2 ) | %iv$
div(A) := grpart( mvectdiff(A,xpos), 0 )$
cross(A,B) := -(A & B) | %iv$

depends([f], [x,y,z])$
declare([f], scalar)$


/* Construct Burger equations in quasilinear form */
dt_f : mvectdiff(f*f/2, xpos)$

/* Split into components and put into a list */
dt_All : [dt_f | ee[1] ]$

meqn : length(dt_All)$

calcev(dir) := block([diff_list,v:ct_coords[dir], Atm, vals, vects, Evs, Rev, Rev_fj, Lev_fj],
  
  diff_list : [ diff(f,x) ],

  Atm : coefmatrix(dt_All, diff_list),
  [vals, vects] : eigenvectors(Atm),
  
  Evs : (Evs : [], for i from 1 thru length(vals[1])
        do (for j from 1 thru vals[2][i]
	  do (Evs : append(Evs, [vals[1][i]]))), Evs),

  Rev : (Rev : matrix([]), for i from 1 thru length (vals[1]) 
        do (for j from 1 thru vals[2][i] 
          do ( (Rev : addcol(Rev, transpose(matrix(vects[i][j])))))), Rev),

  Evs : letsimp( expand(Evs) ),
  Rev : letsimp( Rev ),
  Lev : invert(Rev),

  return ([Evs, Rev, Lev])
  )$

res : calcev(1)$
res[2] : matrix([1])$
res[3] : matrix([1])$

/* Fluxes for conserved variables */
F[d] := [ f*f/2 ]$

/** Code generation is below */
qv : transpose(makelist(q[i-1], i, 1, meqn))$
vv1 : transpose(makelist(v1[i-1], i, 1, meqn))$
vin1 : transpose(makelist(vin[i-1], i, 1, meqn))$

fh : openw("/home/gandalf/research/ammar-simjournal/source/code/hyper-harness/eqn_burgers.h")$
printf(fh, "#pragma once ~%")$
printf(fh, "// Auto-generated code. Do not edit by hand ~%")$
printf(fh, "~%")$
printf(fh, "#include <math.h>~%")$
printf(fh, "~%")$

printf(fh, "~%")$
printf(fh, "static inline double burgers_sq(double x) { return x*x; } ~%")$
printf(fh, "~%")$

printf(fh, "~%")$
printf(fh, "struct burgers_eqn { ~%")$
printf(fh, "  ~%")$
printf(fh, "}; ~%")$
printf(fh, "~%")$

/* Declare functions */

printf(fh, "static void burgers_flux_0(void *ctx, const double *q, double *fout); ~%")$
printf(fh, "static void burgers_flux_1(void *ctx, const double *q, double *fout); ~%")$
printf(fh, "static void burgers_flux_2(void *ctx, const double *q, double *fout); ~%")$
printf(fh, "static void burgers_flux_dot_vec(void *ctx, const double *vec, const double *q, double *fout); ~%")$

printf(fh, "static void burgers_projon_left_ev_0(void *ctx, const double *q, const double *vin, double *vout); ~%")$
printf(fh, "static void burgers_projon_left_ev_1(void *ctx, const double *q, const double *vin, double *vout); ~%")$
printf(fh, "static void burgers_projon_left_ev_2(void *ctx, const double *q, const double *vin, double *vout); ~%")$

printf(fh, "static void burgers_recwith_right_ev_0(void *ctx, const double *q, const double *vin, double *vout); ~%")$
printf(fh, "static void burgers_recwith_right_ev_1(void *ctx, const double *q, const double *vin, double *vout); ~%")$
printf(fh, "static void burgers_recwith_right_ev_2(void *ctx, const double *q, const double *vin, double *vout); ~%")$

printf(fh, "static void burgers_rescale_right_ev_0(void *ctx, const double *q, const double *w, double *revout); ~%")$
printf(fh, "static void burgers_rescale_right_ev_1(void *ctx, const double *q, const double *w, double *revout); ~%")$
printf(fh, "static void burgers_rescale_right_ev_2(void *ctx, const double *q, const double *w, double *revout); ~%")$


printf(fh, "static double burgers_ev_0(void *ctx, const double *q, double *ev); ~%")$
printf(fh, "static double burgers_ev_1(void *ctx, const double *q, double *ev); ~%")$
printf(fh, "static double burgers_ev_2(void *ctx, const double *q, double *ev); ~%")$

printf(fh, "static void burgers_ravg(void *ctx, const double *ql, const double *qr, double *qavg); ~%")$

printf(fh, "static double burgers_fluct_0(void *ctx, const double *ql, const double *qr, double *apdq, double *amdq); ~%")$
printf(fh, "static double burgers_fluct_1(void *ctx, const double *ql, const double *qr, double *apdq, double *amdq); ~%")$
printf(fh, "static double burgers_fluct_2(void *ctx, const double *ql, const double *qr, double *apdq, double *amdq); ~%")$

printf(fh, "static void burgers_rotate_to_local(void *ctx, double n[3], double tau1[3], double tau2[3], const double *qglobal, double *qlocal); ~%")$
printf(fh, "static void burgers_rotate_to_global(void *ctx, double n[3], double tau1[3], double tau2[3], const double *qlocal, double *qglobal); ~%")$

printf(fh, "~%")$

/* Flux in x, y and z direction */
for d : 1 thru 3 do (
  printf(fh, "static inline void ~%burgers_flux_~a(void *ctx, const double *q, double *fout) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  fout[0] = q[0]*q[0]/2; ~%"),
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

/* Flux dotted with vector vec */
printf(fh, "static inline void ~%burgers_flux_dot_vec(void *ctx, const double *vec, const double *q, double *fout) ~%")$
printf(fh, "{ ~%")$
printf(fh, "  fout[0] = q[0]*q[0]/2; ~%")$
printf(fh, "} ~%")$
printf(fh, "~%")$

/* Project on left eigenvectors */
for d : 1 thru 3 do (
  printf(fh, "static void ~%burgers_projon_left_ev_~a(void *ctx, const double *q, const double *vin, double *vout) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  vout[0] = vin[0]; ~%"),
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

/* Reconstruct with right eigenvectors */
for d : 1 thru 3 do (
  printf(fh, "static inline void ~%burgers_recwith_right_ev_~a(void *ctx, const double *q, const double *vin, double *vout) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  vout[0] = vin[0]; ~%"),
  printf(fh, "} ~%"),
  printf(fh, "~%")  
  )$

/* Rescale right eigenvectors */
for d : 1 thru 3 do (
  printf(fh, "static void ~%burgers_rescale_right_ev_~a(void *ctx, const double *q, const double *w, double *revout) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  revout[0] = w[0]; ~%"),
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

/* Eigenvalues */
for d : 1 thru 3 do (
  printf(fh, "static inline double ~%burgers_ev_~a(void *ctx, const double *q, double *ev) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  ev[0] = q[0]; ~%"),
  printf(fh, "  return fabs(ev[0]); ~%", d),
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

/* Roe averages */
printf(fh, "static inline void ~%burgers_ravg(void *ctx, const double *ql, const double *qr, double *qavg) ~%")$
printf(fh, "{ ~%")$

printf(fh, "  qavg[0] = 0.5*(ql[0]+qr[0]); ~%")$

printf(fh, "} ~%")$
printf(fh, "~%")$

/* Fluctuation */
for d : 1 thru 3 do (
  printf(fh, "static inline double ~%burgers_fluct_~a(void *ctx, const double *ql, const double *qr, double *apdq, double *amdq) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "
      double c = 0.5*(ql[0]+qr[0]);
      apdq[0] = fmax(0.0, c)*(qr[0]-ql[0]);
      amdq[0] = fmin(0.0, c)*(qr[0]-ql[0]);      
    "),
  printf(fh, "  return fabs(c); ~%", d),
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

printf(fh, "static inline void ~%burgers_rotate_to_local(void *ctx, double n[3], double tau1[3], double tau2[3], const double *qglobal, double *qlocal) ~%")$
printf(fh, "{ ~%")$
printf(fh, "  qlocal[0] = qglobal[0]; ~%")$
printf(fh, "} ~%")$
printf(fh, "~%")$

printf(fh, "static inline void ~%burgers_rotate_to_global(void *ctx, double n[3], double tau1[3], double tau2[3], const double *qlocal, double *qglobal) ~%")$
printf(fh, "{ ~%")$
printf(fh, "  qglobal[0] = qlocal[0]; ~%")$
printf(fh, "} ~%")$
printf(fh, "~%")$

close(fh)$
