kill(all)$
/* This requires the Clifford algebra package in your Maxima load path */
/* GitHUb: https://github.com/dprodanov/clifford */
load("clifford")$
load("cliffordan")$

clifford(ee,2)$
declare([x, y], scalar)$
ct_coords : [x, y]$
xpos : x*ee[1] + y*ee[2]$

div(A) := grpart( mvectdiff(A,xpos), 0 )$

depends([uu], [x,y])$
depends([h], [x,y])$
declare([g], scalar)$

u : cvect(uu)$

/* Construct shallow water equations in quasilinear form */
dt_rho : grpart(mvectdiff(h*u, xpos), 0)$
dt_u : cliffsimpall( cdirdiff(u, u, xpos) + g*mvectdiff(h,xpos) )$

/* Split into components and put into a list */
dt_All : [dt_rho, dt_u | ee[1], dt_u | ee[2] ]$

meqn : length(dt_All)$

let(u|u, u2)$

/* Transform from primitive to conserved variables */
phi_v : [h, h*(u|ee[1]), h*(u|ee[2])]$
primvec : [h, u|ee[1], u|ee[2] ]$
phi_prime_ij [i,j] := diff(phi_v[i], primvec[j])$
phi_prime : genmatrix(phi_prime_ij, meqn, meqn)$

/** Compute inverse transform */
phi_prime_inv : fullratsimp(invert(phi_prime))$

phi_prime : letsimp(phi_prime)$
phi_prime_inv : letsimp( factor(phi_prime_inv) )$

calcev(dir) := block([diff_list,v:ct_coords[dir], Atm, vals, vects, Evs, Rev, Rev_fj, Lev_fj],
  
  diff_list : [ diff(h,v), diff(uu[1],v), diff(uu[2],v) ],

  Atm : coefmatrix(dt_All, diff_list),
  [vals, vects] : eigenvectors(Atm),
  
  Evs : (Evs : [], for i from 1 thru length(vals[1])
        do (for j from 1 thru vals[2][i]
	  do (Evs : append(Evs, [vals[1][i]]))), Evs),

  Rev : (Rev : matrix([]), for i from 1 thru length (vals[1]) 
        do (for j from 1 thru vals[2][i] 
          do ( (Rev : addcol(Rev, transpose(matrix(vects[i][j])))))), Rev),

  Evs : letsimp( expand(Evs) ),
  Rev : letsimp( Rev ),
  Lev : invert(Rev),

  return ([Evs, Rev, Lev])
  )$

res : calcev(1)$

/** Right/left eigenvectors of flux Jacobian */
Rev_fj : phi_prime . res[2]$
Lev_fj : res[3] . phi_prime_inv$

/* Fluxes for conserved variables */
flux_rho : h*u$
flux_mom[i] := h*(ee[i]|u)*u + 1/2*g*h^2*ee[i]$

F[d] := [ flux_rho | ee[d], flux_mom[d] | ee[1], flux_mom[d] | ee[2] ]$

/** Code generation is below */
qv : transpose(makelist(q[i-1], i, 1, meqn))$
vv1 : transpose(makelist(v1[i-1], i, 1, meqn))$
vin1 : transpose(makelist(vin[i-1], i, 1, meqn))$
slist : [uu[1] = ux, uu[2] = uy, uu[3] = uz, gamma = gas_gamma]$

let(h^2, shallow_water_sq(h))$
let(ux^2, shallow_water_sq(ux))$
let(uy^2, shallow_water_sq(uy))$

fh : openw("/home/gandalf/research/ammar-simjournal/source/code/hyper-harness/eqn_shallow_water.h")$
printf(fh, "#pragma once ~%")$
printf(fh, "// Auto-generated code. Do not edit by hand ~%")$
printf(fh, "~%")$
printf(fh, "#include <math.h>~%")$
printf(fh, "~%")$

printf(fh, "~%")$
printf(fh, "static inline double shallow_water_sq(double x) { return x*x; } ~%")$
printf(fh, "~%")$

printf(fh, "~%")$
printf(fh, "struct shallow_water_eqn { ~%")$
printf(fh, "  double grav; ~%")$
printf(fh, "}; ~%")$
printf(fh, "~%")$

/* Declare functions */
printf(fh, "static void shallow_water_mulby_phi_prime(void *ctx, const double *q, const double *vin, double *vout); ~%")$
printf(fh, "static void shallow_water_mulby_phi_prime_inv(void *ctx, const double *q, const double *vin, double *vout); ~%")$

printf(fh, "static void shallow_water_flux_0(void *ctx, const double *q, double *fout); ~%")$
printf(fh, "static void shallow_water_flux_1(void *ctx, const double *q, double *fout); ~%")$
printf(fh, "static void shallow_water_flux_dot_vec(void *ctx, const double *vec, const double *q, double *fout); ~%")$

printf(fh, "static void shallow_water_projon_left_ev_0(void *ctx, const double *q, const double *vin, double *vout); ~%")$
printf(fh, "static void shallow_water_projon_left_ev_1(void *ctx, const double *q, const double *vin, double *vout); ~%")$

printf(fh, "static void shallow_water_recwith_right_ev_0(void *ctx, const double *q, const double *vin, double *vout); ~%")$
printf(fh, "static void shallow_water_recwith_right_ev_1(void *ctx, const double *q, const double *vin, double *vout); ~%")$

printf(fh, "static void shallow_water_rescale_right_ev_0(void *ctx, const double *q, const double *w, double *revout); ~%")$
printf(fh, "static void shallow_water_rescale_right_ev_1(void *ctx, const double *q, const double *w, double *revout); ~%")$


printf(fh, "static double shallow_water_ev_0(void *ctx, const double *q, double *ev); ~%")$
printf(fh, "static double shallow_water_ev_1(void *ctx, const double *q, double *ev); ~%")$

printf(fh, "static void shallow_water_ravg(void *ctx, const double *ql, const double *qr, double *qavg); ~%")$

printf(fh, "static double shallow_water_roe_fluct_0(void *ctx, const double *ql, const double *qr, double *apdq, double *amdq); ~%")$
printf(fh, "static double shallow_water_roe_fluct_1(void *ctx, const double *ql, const double *qr, double *apdq, double *amdq); ~%")$

printf(fh, "~%")$

/* Define function for multiplying by phi_prime */
printf(fh, "static inline void ~%shallow_water_mulby_phi_prime(void *ctx, const double *q, const double *vin, double *vout) ~%")$
printf(fh, "{ ~%")$
printf(fh, "  struct shallow_water_eqn *eqn = ctx; ~%")$
printf(fh, "  double g = eqn->grav; ~%")$
printf(fh, "  double h = q[0]; ~%")$
printf(fh, "  double ux = q[1]/q[0]; ~%")$
printf(fh, "  double uy = q[2]/q[0]; ~%")$
printf(fh, "  double u2 = ux*ux + uy*uy; ~%")$
out : subst(slist, phi_prime . vin1)$
for i : 1 thru meqn do (
  printf(fh, "  vout[~a] = ~a; ~%", i-1, float(out[i][1]))
  )$

printf(fh, "} ~%")$
printf(fh, "~%")$

/* Define function for multiplying by phi_prime_inv */
printf(fh, "static inline void ~%shallow_water_mulby_phi_prime_inv(void *ctx, const double *q, const double *vin, double *vout) ~%")$
printf(fh, "{ ~%")$
printf(fh, "  struct shallow_water_eqn *eqn = ctx; ~%")$
printf(fh, "  double g = eqn->grav; ~%")$
printf(fh, "  double h = q[0]; ~%")$
printf(fh, "  double ux = q[1]/q[0]; ~%")$
printf(fh, "  double uy = q[2]/q[0]; ~%")$
printf(fh, "  ~%")$
printf(fh, "  double u2 = ux*ux + uy*uy; ~%")$
out : factor( subst(slist, phi_prime_inv . vin1) )$
for i : 1 thru meqn do (
  printf(fh, "  vout[~a] = ~a; ~%", i-1, float(out[i][1]))
  )$

printf(fh, "} ~%")$
printf(fh, "~%")$

/* Flux in x, y and z direction */
for d : 1 thru 2 do (
  printf(fh, "static inline void ~%shallow_water_flux_~a(void *ctx, const double *q, double *fout) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  struct shallow_water_eqn *eqn = ctx; ~%"),
  printf(fh, "  double g = eqn->grav; ~%"),
  printf(fh, "  double h = q[0]; ~%"),
  printf(fh, "  double ux = q[1]/q[0]; ~%"),
  printf(fh, "  double uy = q[2]/q[0]; ~%"),
  printf(fh, "  ~%"),
  printf(fh, "  double u2 = ux*ux + uy*uy; ~%"),
  out : letsimp(subst(slist, F[d])),
  for i : 1 thru meqn do (
    printf(fh, "  fout[~a] = ~a; ~%", i-1, float(out[i]))
  ), 
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

/* Project on left eigenvectors */
for d : 1 thru 2 do (
  printf(fh, "static void ~%shallow_water_projon_left_ev_~a(void *ctx, const double *q, const double *vin, double *vout) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  struct shallow_water_eqn *eqn = ctx; ~%"),
  printf(fh, "  double g = eqn->grav; ~%"),
  printf(fh, "  double h = q[0]; ~%"),
  printf(fh, "  double ux = q[1]/q[0]; ~%"),
  printf(fh, "  double uy = q[2]/q[0]; ~%"),
  printf(fh, "  ~%"),
  printf(fh, "  double u2 = ux*ux + uy*uy; ~%"),
  printf(fh, "  double v1[3]; ~%"),
  printf(fh, "  shallow_water_mulby_phi_prime_inv(ctx, q, vin, v1); ~%"),
  res : calcev(d),
  out : letsimp(subst(slist, res[3] . vv1)),
  for i : 1 thru meqn do (
    printf(fh, "  vout[~a] = ~a; ~%", i-1, float(out[i][1]))
  ),   
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

/* Reconstruct with right eigenvectors */
for d : 1 thru 2 do (
  printf(fh, "static inline void ~%shallow_water_recwith_right_ev_~a(void *ctx, const double *q, const double *vin, double *vout) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  struct shallow_water_eqn *eqn = ctx; ~%"),
  printf(fh, "  double g = eqn->grav; ~%"),
  printf(fh, "  double h = q[0]; ~%"),
  printf(fh, "  double ux = q[1]/q[0]; ~%"),
  printf(fh, "  double uy = q[2]/q[0]; ~%"),
  printf(fh, "  ~%"),
  printf(fh, "  double u2 = ux*ux + uy*uy; ~%"),
  printf(fh, "  double v1[3]; ~%"),
  res : calcev(d),
  out : letsimp(subst(slist, res[2] . vin1)),
  for i : 1 thru meqn do (
    printf(fh, "  v1[~a] = ~a; ~%", i-1, float(out[i][1]))
  ),
  printf(fh, "  shallow_water_mulby_phi_prime(ctx, q, v1, vout); ~%"),
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

/* Rescale right eigenvectors */
for d : 1 thru 2 do (
  printf(fh, "static void ~%shallow_water_rescale_right_ev_~a(void *ctx, const double *q, const double *w, double *revout) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  struct shallow_water_eqn *eqn = ctx; ~%"),
  printf(fh, "  double g = eqn->grav; ~%"),
  printf(fh, "  double h = q[0]; ~%"),
  printf(fh, "  double ux = q[1]/q[0]; ~%"),
  printf(fh, "  double uy = q[2]/q[0]; ~%"),
  printf(fh, "  ~%"),
  printf(fh, "  double u2 = ux*ux + uy*uy; ~%"),
  printf(fh, "  double v1[3]; ~%"),
  printf(fh, "  double *vout; ~%"),  
  res : calcev(d),
  Rev : res[2],
  for i : 1 thru meqn do (
    out : letsimp(subst(slist, w[i-1]*col(Rev,i) )),
    for j : 1 thru meqn do (
      printf(fh, "  v1[~a] = ~a; ~%", j-1, float(out[j][1]))
      ),
    printf(fh, "  vout = &revout[3*~a]; ~%", i-1),
    printf(fh, "  shallow_water_mulby_phi_prime(ctx, q, v1, vout); ~%"),
    printf(fh, "~%")
  ),

  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

/* Eigenvalues */
for d : 1 thru 2 do (
  printf(fh, "static inline double ~%shallow_water_ev_~a(void *ctx, const double *q, double *ev) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  struct shallow_water_eqn *eqn = ctx; ~%"),
  printf(fh, "  double g = eqn->grav; ~%"),
  printf(fh, "  double h = q[0]; ~%"),
  printf(fh, "  double ux = q[1]/q[0]; ~%"),
  printf(fh, "  double uy = q[2]/q[0]; ~%"),
  printf(fh, "  ~%"),
  printf(fh, "  double u2 = ux*ux + uy*uy; ~%"),
  res : calcev(d),
  out : letsimp(subst(slist, res[1])),
  for i : 1 thru meqn do (
    printf(fh, "  ev[~a] = ~a; ~%", i-1, out[i])
  ),
  printf(fh, "  return fabs(q[~a]/q[0]) + sqrt(g*h); ~%", d),
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

/* Roe averages */
printf(fh, "static inline void ~%shallow_water_ravg(void *ctx, const double *ql, const double *qr, double *qavg) ~%")$
printf(fh, "{ ~%")$
printf(fh, "  struct shallow_water_eqn *eqn = ctx; ~%")$
printf(fh, "  double g = eqn->grav; ~%")$

printf(fh, "  double hl = ql[0]; ~%")$
printf(fh, "  double uxl = ql[1]/ql[0]; ~%")$
printf(fh, "  double uyl = ql[2]/ql[0]; ~%")$
printf(fh, "  double u2l = uxl*uxl + uyl*uyl; ~%")$
  
printf(fh, "  double hr = qr[0]; ~%")$
printf(fh, "  double uxr = qr[1]/qr[0]; ~%")$
printf(fh, "  double uyr = qr[2]/qr[0]; ~%")$
printf(fh, "  double u2r = uxr*uxr + uyr*uyr; ~%")$

printf(fh, "  double h = 0.5*(hl+hr); ~%")$
printf(fh, "  double ux = (uxl*sqrt(hl)+uxr*sqrt(hr))/(sqrt(hl)+sqrt(hr)); ~%")$
printf(fh, "  double uy = (uyl*sqrt(hl)+uyr*sqrt(hr))/(sqrt(hl)+sqrt(hr)); ~%")$

printf(fh, "  qavg[0] = h; ~%")$
printf(fh, "  qavg[1] = h*ux; ~%")$
printf(fh, "  qavg[2] = h*uy; ~%")$

printf(fh, "} ~%")$
printf(fh, "~%")$

/* Fluctuation */
for d : 1 thru 2 do (
  printf(fh, "static inline double ~%shallow_water_roe_fluct_~a(void *ctx, const double *ql, const double *qr, double *apdq, double *amdq) ~%", d-1),
  printf(fh, "{ ~%"),
  printf(fh, "  struct shallow_water_eqn *eqn = ctx; ~%"),
  printf(fh, "  double dq[3]; ~%"),
  printf(fh, "
  for (int i=0; i<3; ++i) dq[i] = qr[i]-ql[i];

  double qavg[3];
  shallow_water_ravg(eqn, ql, qr, qavg);

  double w[3];
  shallow_water_projon_left_ev_~a(eqn, qavg, dq, w);
  double wrev[3*3];
  shallow_water_rescale_right_ev_~a(eqn, qavg, w, wrev);
    
  double ev[3];
  shallow_water_ev_~a(eqn, qavg, ev);
  double amax = 0.0;

  for (int i=0; i<3; ++i) {
    amdq[i] = apdq[i] = 0.0;
      
    for (int j=0; j<3; ++j){
      apdq[i] += fmax(0.0, ev[j])*wrev[j*3+i];
      amdq[i] += fmin(0.0, ev[j])*wrev[j*3+i];
    }
    amax = fmax(amax, fabs(ev[i]));
  }
    ", d-1, d-1, d-1),
  printf(fh, "  return amax; ~%", d),
  printf(fh, "} ~%"),
  printf(fh, "~%")
  )$

close(fh)$
